import { Question, QuestionType, DifficultyLevel } from '../types';
import { DocxParsedExam } from './docxParser';

/**
 * Repairs a JSON string generated by LLMs that may contain unescaped LaTeX backslashes,
 * literal newlines inside strings, or trailing commas.
 */
export function repairJsonWithLatex(jsonStr: string): string {
  let result = '';
  let inString = false;
  let i = 0;
  const len = jsonStr.length;

  while (i < len) {
    const char = jsonStr[i];

    if (!inString) {
      if (char === '"') {
        inString = true;
        result += '"';
      } else {
        result += char;
      }
      i++;
    } else {
      // Inside a string literal
      if (char === '"') {
        // Count preceding backslashes to check if this quote is escaped
        let backslashCount = 0;
        let k = i - 1;
        while (k >= 0 && jsonStr[k] === '\\') {
          backslashCount++;
          k--;
        }
        if (backslashCount % 2 === 0) {
          // Quote is not escaped, ends the string literal
          inString = false;
          result += '"';
          i++;
        } else {
          // Escaped quote: \"
          result += '"';
          i++;
        }
      } else if (char === '\\') {
        // Look ahead to check what follows the backslash
        const nextChar = i + 1 < len ? jsonStr[i + 1] : '';
        const restOfStr = jsonStr.substring(i + 1, Math.min(len, i + 15));

        // LaTeX commands starting with n, t, f, r, b that collide with JSON escapes (\n, \t, \f, \r, \b):
        const latexN = /^(eq|abla|ot|ewline|otin|approx|cong|mid|parallel|subseteq|supset|supseteq)/i;
        const latexT = /^(an|imes|heta|au|ext|o|ilde|frac|binom)/i;
        const latexF = /^(rac|orall|lat|rown)/i;
        const latexR = /^(ight|ho|angle|floor|ceil|adical|angle)/i;
        const latexB = /^(egin|eta|ar|m|mod|ullet|ig|matrix|subset|supset)/i;

        if (nextChar === '\\' || nextChar === '"' || nextChar === '/') {
          result += '\\' + nextChar;
          i += 2;
        } else if (nextChar === 'n' && latexN.test(restOfStr.substring(1))) {
          // It's \neq or \notin, not a newline!
          result += '\\\\n';
          i += 2;
        } else if (nextChar === 't' && latexT.test(restOfStr.substring(1))) {
          // It's \tan, \times, \theta, \text, not a tab!
          result += '\\\\t';
          i += 2;
        } else if (nextChar === 'f' && latexF.test(restOfStr.substring(1))) {
          // It's \frac or \forall, not form feed!
          result += '\\\\f';
          i += 2;
        } else if (nextChar === 'r' && latexR.test(restOfStr.substring(1))) {
          // It's \right or \rho, not carriage return!
          result += '\\\\r';
          i += 2;
        } else if (nextChar === 'b' && latexB.test(restOfStr.substring(1))) {
          // It's \begin, \beta, \bar, not backspace!
          result += '\\\\b';
          i += 2;
        } else if (nextChar === 'u' && /^[0-9a-fA-F]{4}/.test(jsonStr.substring(i + 2, i + 6))) {
          // Valid unicode escape \uXXXX
          result += '\\u' + jsonStr.substring(i + 2, i + 6);
          i += 6;
        } else if (nextChar === 'n' || nextChar === 'r' || nextChar === 't' || nextChar === 'b' || nextChar === 'f') {
          // Valid standard JSON escape character (\n, \r, \t, etc.)
          result += '\\' + nextChar;
          i += 2;
        } else {
          // Invalid JSON escape (e.g. \sin, \alpha, \pi, \le, \ge, \vec, \Delta, \$, \{, \}, etc.)
          // Double the backslash so JSON.parse receives \sin, \alpha, etc.
          result += '\\\\';
          i++; // Keep nextChar to be processed on next iteration
        }
      } else if (char === '\n') {
        // Literal newline inside JSON string
        result += '\\n';
        i++;
      } else if (char === '\r') {
        // Literal carriage return inside JSON string
        i++;
      } else if (char === '\t') {
        // Literal tab inside JSON string
        result += '\\t';
        i++;
      } else {
        result += char;
        i++;
      }
    }
  }

  // Remove trailing commas before closing braces/brackets (e.g. [1, 2, ] or {"a": 1, })
  result = result.replace(/,\s*([\}\]])/g, '$1');

  return result;
}

/**
 * Safely parses JSON returned by an AI model, handling markdown fences,
 * preamble/postamble text, and unescaped LaTeX mathematical symbols.
 */
export function safeParseAiJson<T = any>(rawText: string): T {
  if (!rawText || !rawText.trim()) {
    throw new Error('Nội dung phản hồi từ AI rỗng');
  }

  let cleaned = rawText.trim();

  // 1. Strip markdown code block wrappers
  if (cleaned.startsWith('```json')) {
    cleaned = cleaned.replace(/^```json\s*/i, '').replace(/\s*```$/i, '').trim();
  } else if (cleaned.startsWith('```')) {
    cleaned = cleaned.replace(/^```\s*/i, '').replace(/\s*```$/i, '').trim();
  }

  // 2. Extract outermost JSON object {...} or array [...]
  const firstBrace = cleaned.indexOf('{');
  const firstBracket = cleaned.indexOf('[');
  let startIdx = -1;
  let endIdx = -1;

  if (firstBrace !== -1 && (firstBracket === -1 || firstBrace < firstBracket)) {
    startIdx = firstBrace;
    endIdx = cleaned.lastIndexOf('}');
  } else if (firstBracket !== -1) {
    startIdx = firstBracket;
    endIdx = cleaned.lastIndexOf(']');
  }

  if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
    cleaned = cleaned.substring(startIdx, endIdx + 1);
  }

  // 3. Attempt direct JSON.parse
  try {
    return JSON.parse(cleaned);
  } catch (initialErr) {
    // If failed, proceed to LaTeX-aware repair
    try {
      const repaired = repairJsonWithLatex(cleaned);
      return JSON.parse(repaired);
    } catch (secondErr: any) {
      console.warn('Second parse attempt failed, trying aggressive repair...', secondErr);
      
      // Aggressive repair: replace all single backslashes that are not already doubled
      try {
        const aggressive = cleaned
          .replace(/\\/g, '\\\\')
          .replace(/\\\\\\\\/g, '\\\\')
          .replace(/\\\\"/g, '\\"')
          .replace(/,\s*([\}\]])/g, '$1');
        return JSON.parse(aggressive);
      } catch (thirdErr: any) {
        throw new Error(`Không thể giải mã cấu trúc JSON từ AI: ${secondErr.message || initialErr.message}`);
      }
    }
  }
}

/**
 * Normalizes an exam data object parsed from AI into standard DocxParsedExam format
 */
export function normalizeAiExamData(examData: any, defaultLessonTitle: string): DocxParsedExam {
  const rawQuestions: any[] = Array.isArray(examData) ? examData : (examData.questions || []);

  const normalizedQuestions: Question[] = rawQuestions.map((q: any, idx: number) => {
    // Determine Part
    let part: 1 | 2 | 3 | 4 = 1;
    if (q.part === 1 || q.part === 2 || q.part === 3 || q.part === 4) {
      part = q.part;
    } else if (q.type === QuestionType.MULTIPLE_CHOICE || q.type === 'MULTIPLE_CHOICE') {
      part = 1;
    } else if (q.type === QuestionType.TRUE_FALSE || q.type === 'TRUE_FALSE') {
      part = 2;
    } else if (q.type === QuestionType.SHORT_ANSWER || q.type === 'SHORT_ANSWER') {
      part = 3;
    } else if (q.type === QuestionType.ESSAY || q.type === 'ESSAY') {
      part = 4;
    }

    // Determine Question Type
    let type: QuestionType = QuestionType.MULTIPLE_CHOICE;
    if (part === 1) type = QuestionType.MULTIPLE_CHOICE;
    else if (part === 2) type = QuestionType.TRUE_FALSE;
    else if (part === 3) type = QuestionType.SHORT_ANSWER;
    else if (part === 4) type = QuestionType.ESSAY;

    // Difficulty
    let difficulty: DifficultyLevel = DifficultyLevel.THONG_HIEU;
    if (q.difficulty && Object.values(DifficultyLevel).includes(q.difficulty)) {
      difficulty = q.difficulty;
    }

    // Points
    const points = q.points || (part === 1 ? 0.25 : part === 2 ? 1.0 : part === 3 ? 0.5 : 1.5);

    // Options for Part 1
    const options = (q.options || []).map((opt: any) => ({
      id: String(opt.id || opt.label || 'A').toUpperCase(),
      label: String(opt.id || opt.label || 'A').toUpperCase(),
      content: String(opt.content || opt.text || '').trim()
    }));

    // True/False Items for Part 2
    const trueFalseItems = (q.trueFalseItems || q.statements || []).map((tf: any) => ({
      id: String(tf.id || tf.label || 'a').toLowerCase(),
      label: String(tf.id || tf.label || 'a').toLowerCase(),
      content: String(tf.content || tf.text || '').trim(),
      correctAnswer: tf.correctAnswer === true || tf.correctAnswer === 'true' || tf.correctAnswer === 'Đúng',
      explanation: tf.explanation || ''
    }));

    // Short Answer Config for Part 3
    let shortAnswerConfig = q.shortAnswerConfig;
    if (!shortAnswerConfig && (q.correctAnswer || q.answer)) {
      shortAnswerConfig = {
        correctAnswers: [String(q.correctAnswer || q.answer).trim()]
      };
    }

    return {
      id: q.id || `ai_q_${part}_${idx + 1}`,
      part,
      questionNumber: q.questionNumber || (idx + 1),
      type,
      difficulty,
      points,
      content: String(q.content || q.stem || '').trim(),
      options: part === 1 ? options : undefined,
      correctOption: part === 1 ? (q.correctOption || q.correctAnswer || 'A') : undefined,
      trueFalseItems: part === 2 ? trueFalseItems : undefined,
      statements: part === 2 ? trueFalseItems : undefined,
      shortAnswerConfig: part === 3 ? shortAnswerConfig : undefined,
      essayGuide: part === 4 ? (q.essayGuide || q.rubric || '') : undefined,
      solution: String(q.solution || q.explanation || '').trim()
    };
  });

  return {
    title: examData.title || `Luyện tập: ${defaultLessonTitle}`,
    questions: normalizedQuestions,
    rawText: JSON.stringify(examData, null, 2),
    warnings: [],
    hasUnconfidentFormulas: false
  };
}
